variables:
    IMAGE_NAME: malek7/my-docker-repo
    IMAGE_TAG: fake-shop-1.0
    
stages:
  - compile
  - test
  - package
  - build-image
  

cache:
  paths:
    - .m2/repository

compile-job:
  image: maven:3.8.6-openjdk-18
  stage: compile
  script:
    - mvn compile

test-job:
  image: maven:3.8.6-openjdk-18
  stage: test
  script:
    - mvn test

package-job: 
  image: maven:3.8.6-openjdk-18
  stage: package
  script:
    - mvn package

  artifacts:
    paths:
      - target/

build-image :
  image: docker:20.10.21
  services:
    - docker:20.10.21-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  stage: build-image
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  
  dependencies:
    - package-job

