image: maven:3.8.6-openjdk-18

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository

build-code-job:
  stage: build
  script:
    - mvn failghfsduifhauifhauiodfhaduifhuidasfhuia

test-code-job1:
  stage: test
  script:
    - mvn test
