image: maven:3.8.6-openjdk-18

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository

build-code-job:
  stage: build
  script:
    - mvn compile

test-code-job1:
  stage: test
  script:
    - mvn test

docker-build:
    image: docker:latest
    stage: build
    services:
      - docker:dind
    before_script:
      - docker login -u "$CI_REGISTRYUSER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
      - docker build --pull -t "$CI_REGISTRY_IMAGE"
      - docker push "CI_REGISTRY_IMAGE"

