
variables:
    IMAGE_NAME: malek7/my-docker
    IMAGE_TAG: fake-shop-1.0
    
stages:
  - compile
  - test
  - build-image

cache:
  paths:
    - .m2/repository

pre:
  image: maven:3.8.6-openjdk-18
  stage: build
  script:
    - mvn compile

test:
  image: maven:3.8.6-openjdk-18
  stage: test
  script:
    - mvn test

build-image:
  image: docker:20.10.21
  services:
    - docker:20.10.21-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $DOCKER_USER -p DOCKER_PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
