image: maven:3.8.6-openjdk-18

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository

build-code-job:
  stage: build
  script:
    - mvn compile

test-code-job1:
  stage: test
  script:
    - mvn test


variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DOCKER_TLS_CERTDIR: "/certs"


build-push-docker-image-job:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG